{
  callPackage,
  fetchurl,
  gnused,
  imagemagick,
  lib,
  manuals,
  modulesPath,
  nixos-modules,
  perl,
  pkgs,
  python3,
  stdenv,
  texlive,
  version,
  writeText,
  ...
}:
let
  common = stdenv.mkDerivation (finalAttrs: {
    pname = "NGIpkgs-Manuals-${finalAttrs.passthru.format}";
    inherit version;
    src =
      with lib.fileset;
      toSource {
        root = ../.;
        fileset = intersection (gitTracked ../.) (unions [
          (fileFilter (
            file:
            lib.any file.hasExt [
              "md"
              "nix"
              "svg"
            ]
          ) ../.)
          ./Makefile
          ./_ext
          ./_redirects
          ./_static
          ./_templates
          ./conf.py
          ./favicon.png
          ./netlify.toml
          ./robots.txt
          ../projects
        ]);
      };

    nativeBuildInputs = [
      finalAttrs.passthru.pythonPackages
      gnused
      perl
      imagemagick
    ];

    patchPhase = ''
      runHook prePatch
      magick ${finalAttrs.passthru.logo} manuals/_static/_img/nix.pdf
      substituteInPlace manuals/index.md \
        --replace-fail '@MANUALS_VERSION@' "${version}"
      runHook postPatch
    '';

    buildPhase = ''
      runHook preBuild
      make -C manuals ${finalAttrs.passthru.format}
      runHook postBuild
    '';

    passthru = {
      logo = fetchurl {
        url = "https://brand.nixos.org/logos/nixos-logomark-default-gradient-minimal.svg";
        hash = "sha256-YrOle9qo0G92vvCjy9FAkyNOdyAz1DR+xoc+/CpK0yk=";
      };
      pythonPackages = python3.withPackages (
        pyPkgs: with pyPkgs; [
          linkify-it-py
          myst-parser
          sphinx
          sphinx-book-theme
          sphinx-copybutton
          sphinx-design
          sphinx-notfound-page
          sphinx-sitemap
        ]
      );
    };
  });
in
# Explanation: split the different formats
# in different derivations instead of different outputs
# in order to only use `nix build -f. manuals.singlehtml`
# as a `.git/hooks/pre-push` check.
lib.recurseIntoAttrs {
  html = common.overrideAttrs (previousAttrs: {
    installPhase = ''
      runHook preInstall
      cp -R manuals/build/html $out/
      cp manuals/netlify.toml $out/
      runHook postInstall
    '';
    passthru = previousAttrs.passthru or { } // {
      format = "html";
    };
  });

  latexpdf = common.overrideAttrs (
    finalAttrs: previousAttrs: {
      nativeBuildInputs = previousAttrs.nativeBuildInputs or [ ] ++ [
        finalAttrs.passthru.texPackages
      ];
      installPhase = ''
        runHook preInstall
        install -Dm444 manuals/build/latex/NGIpkgs_Manuals.pdf $out/NGIpkgs_Manuals.pdf
        runHook postInstall
      '';
      passthru = previousAttrs.passthru or { } // {
        format = "latexpdf";
        # Explanation: those TeX packages are dependencies to provision
        # for the build/latex/*.{tex,sty} files generated by sphinx,
        # ./tex-env.nix has itself been generated with:
        # nix run github:rgri/tex2nix -- build/latex/*.{tex,sty}
        texPackages = callPackage ./tex-env.nix {
          extraTexPackages = {
            inherit (texlive)
              latexmk
              collection-fontsrecommended
              collection-latexrecommended
              collection-luatex
              gnu-freefont # For FreeSerif.otf
              ;
          };
        };
      };
    }
  );

  singlehtml = common.overrideAttrs (previousAttrs: {
    passthru = previousAttrs.passthru or { } // {
      format = "singlehtml";
    };
    installPhase = ''
      runHook preInstall
      cp -R manuals/build/singlehtml $out/
      cp manuals/netlify.toml $out/
      runHook postInstall
    '';
  });
}
